const VALIDATION_ERROR = 400;
const UNAUTHORIZED_ERROR = 401;
const ERROR_NOT_FOUND = 404;
const SERVER_ERROR = 500;

module.exports = {
  VALIDATION_ERROR, UNAUTHORIZED_ERROR, ERROR_NOT_FOUND, SERVER_ERROR,
};
